language: python
python:
  - "3.4"
# command to install dependencies
install: 
  - pip3 install -q -U setuptools tox
    
# command to run tests
script: tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: required
